- book-sum.php
- inc/ffboka/item.php
- userdata.php
> Fix unavailable status in booking-sum

- book-sum.php
- inc/ff-boka.js
- index.php
- userdata.php
Make it an ajax request.
Redirect to user page for logged-in users, and to index for guests.
Fixes issue #40.
> Improve delete booking.

- .gitignore
- inc/ffboka/ffboka.php
Warning message caused json data to be corrupted
> More error handling for image upload

- inc/common.php
- inc/config.php
- inc/ffboka/ffboka.php
- inc/ffboka/user.php
- index.php
- userdata.php
> Implement connection to API for authentication

- admin/bookings-d.php
- book-part.php
- book-sum.php
- css/ff-boka.css
- inc/ff-boka.js
- inc/ffboka/item.php
> Better date picker, more comments in JS file

- admin/category.php
- book-sum.php
- inc/ff-boka.js
- inc/ffboka/category.php
- inc/ffboka/user.php
- templates/confirm_booking.html
Rework of cat contact information, adding possibility to store
non-member information.
> Send contact information with booking

- book-part.php
> Hide freebusy bar if user lacks permissions to see it

- book-part.php
- inc/ffboka/item.php
> Show coming bookings in item detail popup

- admin/bookings-d.php
- book-sum.php
- css/ff-boka.css
- inc/common.php
- inc/config.php
> Add function to add bookings on behalf of others

- admin/bookings-d.php
- book-part.php
- book-sum.php
- css/ff-boka.css
- inc/common.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/category.php
- inc/ffboka/item.php
- inc/ffboka/user.php
Final work on issue #29 for first working booking admin version.
> Set price, set paid sum and more

- admin/bookings-d.php
- admin/item.php
- css/ff-boka.css
- item-details.php
> Link item caption to item detail view in side panel

- book-sum.php
- index.php
> Better redirect for booking summary

- README.md
- admin/bookings-d.php
- cron.php
- css/ff-boka.css
- inc/config.php
- inc/credentials.sample.php
- inc/ffboka/section.php
- inc/ffboka/user.php
- index.php
Mixed changes, and prepare to show unconfirmed items in booking admin
> Issue58 alerts

- admin/bookings-d.php
- admin/category.php
- admin/index.php
- admin/item.php
- book-part.php
- book-sum.php
- cookies.php
- help.php
- image.php
- inc/common.php
- inc/ff-boka.js
- inc/ffboka/user.php
- index.php
- item-details.php
- userdata.php
> Make URLs working even if not installed in document root

- inc/common.php
- inc/config.php
- inc/ff-boka.js
- inc/ffboka/ffboka.php
- inc/ffboka/user.php
- index.php
- userdata.php
> Rework remember-me feature, add current sessions to user data page

- inc/common.php
- inc/ffboka/ffboka.php
- inc/ffboka/user.php
- index.php
- templates/confirm_mail_address.html
- userdata.php
> Implement verification of email address in user data

- admin/category.php
- admin/index.php
- admin/item.php
- book-part.php
- book-sum.php
- cookies.php
- inc/common.php
- inc/ff-boka.js
- item-details.php
- templates/confirm_mail_address.html
- templates/notify_new_admin.html
- userdata.php
> Notify new admins about their new role

- inc/ffboka/ffboka.php
- index.php
> Prepare landing page for many sections

- inc/ffboka/ffboka.php
- index.php
> Better error message if login API not available

- admin/category.php
- admin/item.php
- inc/ffboka/category.php
- inc/ffboka/item.php
and some minor bug fixes. Implements issue #99
> Add function to move item to other category

- admin/category.php
- index.php
> Add better help text on first page

- admin/item.php
- inc/ffboka/item.php
Conserve Featured item in copy.
Increment number in item caption if captions ends on (n)
> Improved cloning of items

- inc/ffboka/ffboka.php
- index.php
> Allow personnummer for login

- admin/bookings-d.php
> Enable audio playback for notifications

- inc/common.php
- inc/ffboka/user.php
- resources/db/3.sql
> Remove foreign key contraint from database

- inc/ffboka/user.php
- index.php
- userdata.php
> Better handling och change mail process

- cron.php
- inc/common.php
- inc/ffboka/ffboka.php
- inc/ffboka/user.php
- resources/db/4.sql
- userdata.php
Get userAgent information from https://user-agents.net/parser for better
readability of permanent logins
> Implement userAgent lookup

- cron.php
- inc/config.sample.php
> Update incomplete user agents

- book-sum.php
- inc/ff-boka.js
> Use same time for added items as for existing ones

- admin/category.php
- inc/ffboka/category.php
> Sort items in natural order

- admin/item.php
- inc/common.php
- inc/ff-boka.js
- inc/ffboka/item.php
- item-details.php
- resources/db/6.sql
> Add field for internal item notes

- userdata.php
> Better display of user's bookings

- composer.json
- composer.lock
- resources/db/6.sql
Reduce size of note field in items table. 65000 is too big for varchar fields with utf8 encoding and causes errors in the db upgrade process v6.
> Reduce size of note field

- admin/bookings-d.php
- book-part.php
- css/ff-boka.css
- inc/ff-boka.js
- inc/ffboka/ffboka.php
- inc/ffboka/item.php
> Booking admin

- book-part.php
- book-sum.php
> Show item start and end for all authorized users

- admin/superadmin.php
- book-sum.php
- css/ff-boka.css
- inc/common.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/ffboka.php
- inc/version.php
- index.php
- resources/db/13.sql
- templates/alert_series_created.html
- userdata.php
> Repeated bookings

- book-sum.php
- inc/ffboka/booking.php
> add check for overlapping items in booking

- inc/common.php
- inc/config.sample.php
- inc/ffboka/ffboka.php
- inc/version.php
- resources/db/14.sql
- sendmail.php
- test.php
> Implement asynchronous sending of emails

- admin/bookings-m.php
- admin/superadmin.php
- cron.php
- inc/ffboka/ffboka.php
- sendmail.php
> Mail by cron

- admin/index.php
- inc/ffboka/section.php
- index.php
> Add alerts for unconfirmed bookings

- admin/category.php
- css/ff-boka.css
- inc/config.sample.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/category.php
- inc/tagging.js
> email address validation

- admin/index.php
> No alert if sendAlertTo is set

- admin/item.php
- admin/superadmin.php
- inc/config.sample.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/item.php
- inc/version.php
- resources/db/19.sql
> Add item postbook messages

- inc/ffboka/item.php
> Add postbookMsg and note to cloned item

- css/ff-boka.css
- inc/ffboka/item.php
> Different icon for paid bookings

- admin/bookings-d.php
- admin/category.php
- inc/ffboka/item.php
> Add nonsense parameter to make link unique

- admin/category.php
- inc/ff-boka.js
> Update category data if cat is moved

- inc/ff-boka.js
> Update page title if caption changed

- admin/category.php
- image.php
> Force reload of cat image

- cron.php
> Add attachment files to garbage collection

- book-sum.php
- cron.php
- inc/config.sample.php
- inc/ffboka/booking.php
- inc/ffboka/category.php
- inc/ffboka/ffboka.php
- index.php
- userdata.php
Rework of email sending. Confirmation emails and mail address activation messages are now sent immediately without passing the queue.
> Direct mails #307

- admin/category.php
- admin/index.php
- inc/ff-boka.js
- inc/ffboka/category.php
- inc/version.php
- resources/db/21.sql
Fixes #322 
Inherited permissions are now only shown if not overwritten. Also, permissions can be downgraded by overwriting, including the removal of all permissions.
> Rework permissions

- inc/ffboka/category.php
- inc/ffboka/ffboka.php
- inc/ffboka/section.php
- inc/ffboka/user.php
- index.php
Fixes #329 by including item captions. Also changes structure and logic for finding similarity of strings.
> Rework search function

- admin/bookings-d.php
- admin/bookings-m.php
- admin/index.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/ffboka.php
Count bookings instead of items.
Even some minor fixes.
> Rework of indicator for unconfirmed bookings

- admin/superadmin.php
- inc/common.php
- inc/config.sample.php
- inc/ff-boka.js
Remove built-in upgrade code. Upgrades shall be done directly by git or remotely by git-ftp.
Add codebase information to superadmin.
Add maintenance mode.
Add config file check.
Fixes #326.
> Rework of several superadmin features

- admin/item.php
Implements part of #14 by opening the booking interface with a preselected resource. This PR adds the direct link to admin interface.
> Add direct link

- admin/bookings-d.php
- admin/bookings-m.php
- admin/category.php
- admin/index.php
- admin/item.php
- admin/superadmin.php
- admin/usage.php
- ajax.php
- book-part.php
- book-sum.php
- inc/common.php
- inc/ff-boka.js
- inc/ffboka/booking.php
- inc/ffboka/ffboka.php
- inc/ffboka/section.php
- inc/version.php
- index.php
- resources/db/24.sql
- userdata.php
Move ajax to own files.
Format code with spaces.
Add dirty flag to bookings.
Avoid reloading page, use ajax instead.
Rework of user data interface.
Many small fixes.
> Major upgrade spring 2022

- userdata.php
> Change sort order of My Bookings

- cookies.php
- inc/common.php
- inc/ff-boka.js
- index.php
- userdata.php
Resolves #370
Removes some cookie consent handling because we do not use strange cookies.
> Require password on delete, simplify cookies

- admin/ajax.php
- admin/category.php
- admin/index.php
- ajax.php
- book-part.php
- inc/ff-boka.js
- inc/ffboka/category.php
- inc/ffboka/ffboka.php
- inc/version.php
- resources/db/26.sql
- userdata.php
Add an active flag to categories. With the flag unset, a category will not be shown in the booking flow.
Implements #376
> Add active flag to categories

- admin/superadmin.php
- ajax.php
- book-sum.php
- cron.php
- inc/ffboka/booking.php
- inc/ffboka/category.php
- inc/ffboka/item.php
- inc/ffboka/section.php
- inc/ffboka/user.php
- inc/version.php
- index.php
- resources/db/27.sql
- templates/reminder.html
- userdata.php
> Alphanumerical bookingId, and code cleanup

- css/ff-boka.css
> Make all image urls relative to css file

- admin/ajax.php
- admin/bookings-d.php
- admin/category.php
- admin/item.php
- ajax.php
- composer.json
- composer.lock
- inc/common.php
- inc/ff-boka.js
- item-details.php
> Add support for Markdown to item description
